#!/bin/bash

while getopts "d:p:" arg #选项后面的冒号表示该选项需要参数
do
    case $arg in
        d)
            # echo "d's arg:$OPTARG" #参数存在$OPTARG中
            dist=$OPTARG
            ;;
        p)
            path=$OPTARG
            ;;
        ?)  #当有不认识的选项的时候arg为?
            echo "未知参数"
        exit 1
        ;;
        esac
done

# git fetch origin
# git checkout master
# git diff master origin/master
# for ((;;))
# do
#     echo '请确保更新内容是否可被发布.'
#     echo -n '你确定要拉取并发布  origin/master 分支的内容吗? (y/n) '
#     read result
#     if [[ "$result" == [yY] ]]
#     then
#     	break
#     elif [[ "$result" == [nN] ]]
#     then
#     	exit
#     fi
# done

if [[ "$dist" == "" ]]
then
    dist='./dist'
fi

if [[ "$path" == "" ]]
then
    path='http://m.qmin91.com/'
fi
 
echo '正在拉取 origin/master...'
 
# git pull || exit
 
echo '发布中...'

NODE_ENV=production node build/webpack.production.js $dist $path 
 