// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/65ede6d2f3f95b2cff04caa2cefd951ca9ce0521/react-swipeable-views/react-swipeable-views.d.ts
declare namespace ReactSwipeableViews {
    import React = __React;

    export interface SwipeableViewsProps extends React.Props<SwipeableViews> {
        containerStyle?: React.CSSProperties;
        disabled?: boolean;
        index?: number;
        onChangeIndex?: (indexNew:number, indexLatest:number) => void;
        onSwitching?: (index:number) => void;
        resistance?: boolean;
        slideStyle?: React.CSSProperties;
        style?: React.CSSProperties;
        threshold?: number;
    }

    interface SwipeableViewsState {
        indexCurrent?: number;
        indexLatest?: number;
        isDragging?: boolean;
        isFirstRender?: boolean;
        heightLatest?: number;
    }

    export class SwipeableViews extends React.Component<SwipeableViewsProps, SwipeableViewsState> {
    }
}

declare module 'react-swipeable-views' {
    export default ReactSwipeableViews.SwipeableViews;
}
