// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8841dfc744bce6b2d3e075f7ace25c0c1e664c17/react-swipeable/index.d.ts
declare namespace ReactSwipeableModule {
    import React = __React;

    interface onSwipingCallback {
        (event: TouchEvent, deltaX: number, deltaY: number, absX: number, absY: number, velocity: number): void;
    }

    interface OnSwipedCallback {
        (event: TouchEvent, deltaX: number, deltaY: number, isFlick: boolean, velocity: number): void;
    }

    interface OnSwipedDirectionCallback {
        (event: TouchEvent, delta: number, isFlick: boolean): void;
    }

    interface OnSwipingDirectionCallback {
        (event: TouchEvent, delta: number): void;
    }

    interface Props {
        onSwiped?: OnSwipedCallback;
        onSwiping?: onSwipingCallback;
        onSwipingUp?: OnSwipingDirectionCallback;
        onSwipingRight?: OnSwipingDirectionCallback;
        onSwipingDown?: OnSwipingDirectionCallback;
        onSwipingLeft?: OnSwipingDirectionCallback;
        onSwipedUp?: OnSwipedDirectionCallback;
        onSwipedRight?: OnSwipedDirectionCallback;
        onSwipedDown?: OnSwipedDirectionCallback;
        onSwipedLeft?: OnSwipedDirectionCallback;
        flickThreshold?: number;
        delta?: number;
        preventDefaultTouchmoveEvent?: boolean;
        nodeName?: string;
        stopPropagation?: boolean;
        trackMouse?: boolean;
    }

    interface ReactSwipeable extends React.ComponentClass<Props> { }

}


declare module "react-swipeable" {
    let module: ReactSwipeableModule.ReactSwipeable;
    export = module;
}
